baseURL = 'https://jsonnorm.codes/'
languageCode = 'en-us'
title = 'JSON Normalized Expression'
theme = 'hugo-theme-techdoc'

[params]
    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
[markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true 
